const data = {
  locations: [
    {
      /* ------- Los Angeles, CA ----------- */
      locationName: 'Los Angeles, CA',
      hotels: [
        {
          id: '01',
          name: 'Hilton Los Angeles Airport',
          address: '5711 W Century Blvd, Los Angeles, CA 90041 US',
          distance: 1.0,
          price: 110.5,
          image: 'https://i.imgur.com/uC6Bekk.png',
          imageCircle: 'https://i.imgur.com/x4eIVem.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
        {
          id: '02',
          name: 'DoubleTree Los Angeles',
          address: '535 South Grand Avenue, Los Angeles, CA 90071 US',
          distance: 1.2,
          price: 105,
          image: 'https://i.imgur.com/jijV2re.png',
          imageCircle: 'https://i.imgur.com/VRm8Erq.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
        {
          id: '03',
          name: 'The Beverly Hilton',
          address: '9876 Wilshire Blvd, Beverly Hills, CA, US, 90210',
          distance: 2.0,
          price: 185.5,
          image: 'https://i.imgur.com/Yk1DRZ5.png',
          imageCircle: 'https://i.imgur.com/c6CrRk9.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
        {
          id: '04',
          name: 'Hilton Checkers Los Angeles',
          address: '535 South Grand Avenue, Los Angeles, CA 90071 US',
          distance: 2.2,
          price: 126.0,
          image: 'https://i.imgur.com/lQPf93K.png',
          imageCircle: 'https://i.imgur.com/HANo6yB.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
        {
          id: '05',
          name: 'Hilton Pasadena',
          address: '168 South Los Robles Ave, Pasadena, CA 91101 US',
          distance: 2.5,
          price: 175,
          image: 'https://i.imgur.com/8hrAX0A.png',
          imageCircle: 'https://i.imgur.com/uPpWdAX.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
        {
          id: '06',
          name: 'Hilton Universal City',
          address: '555 Universal Hollywood Dr, Universal City, CA 91608 US',
          distance: 2.8,
          price: 258,
          image: 'https://i.imgur.com/BMvTesx.png',
          imageCircle: 'https://i.imgur.com/GxB8A4W.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
        {
          id: '07',
          name: 'Hilton Garden Inn Segundo',
          address: '2100 East Mariposa Ave, El Segundo, CA 90245',
          distance: 3.0,
          price: 131,
          image: 'https://i.imgur.com/dwOkABr.png',
          imageCircle: 'https://i.imgur.com/vJisUmq.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
        {
          id: '08',
          name: 'Hilton Long Beach',
          address: '701 West Ocean Blvd, Long Beach, CA 90831 US',
          distance: 4.5,
          price: 128,
          image: 'https://i.imgur.com/ZZxPzqN.png',
          imageCircle: 'https://i.imgur.com/xQxPS5l.gif',
          cityId: '5c43f218bede3a2ef82f071b',
        },
      ],
    },
    {
      /* ------- Washington, DC ----------- */
      locationName: 'Washington, DC',
      hotels: [
        {
          id: '09',
          name: 'Washington Hilton',
          address: '1919 Connecticut Ave NW, Washington, DC 20009 US',
          distance: 2.0,
          price: 98,
          image: 'https://i.imgur.com/WtMMDvk.png',
          imageCircle: 'https://i.imgur.com/STau9QH.gif',
          cityId: '5c43f208bede3a2ef82f071a',
        },
        {
          id: '10',
          name: 'The Darcy Washington DC',
          address: ' 1515 Rhode Island Avenue NW, Washington, DC 20005 US',
          distance: 3.8,
          price: 106,
          image: 'https://i.imgur.com/GsyJ6lS.png',
          imageCircle: 'https://i.imgur.com/Bxju0QU.gif',
          cityId: '5c43f208bede3a2ef82f071a',
        },
      ],
    },
  ],
};

export default data;
